version: "3.4"

services:
  mongodb:
    image: mongo:4.4.18
    restart: always
    container_name: mongodb
    volumes:
      - /dev:/dev
      - ./data-node:/data/db
    ports:
      - 27020:27017
    command: mongod --noauth
