version: "3.4"

services:
  api:
    depends_on:
      - mongodb
    image: node-api
    build:
      context: .
      target: node-api
      network: host
    restart: always
    network_mode: host
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://0.0.0.0:27017/chatgpt-clone
    volumes:
      - /dev:/dev
      - ./api:/api
      - /api/node_modules
  mongodb:
    image: mongo:4.4.18
    restart: always
    network_mode: host
    container_name: mongodb
    volumes:
      - /dev:/dev
      - ./data-node:/data/db
    command: mongod --noauth
