version: "3.4"

services:
  react-client:
    image: react-client
    build:
      context: .
      target: react-client
      network: host
    volumes:
      - /dev:/dev
      - ./client:/client
      - /client/node_modules
  api:
    depends_on:
      - react-client
      - mongodb
    image: node-api
    build:
      context: .
      target: node-api
      network: host
    restart: always
    network_mode: host
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
    volumes:
      - /dev:/dev
      - ./api:/api
      - /api/node_modules
  mongodb:
    image: mongo:4.4.18
    restart: always
    network_mode: host
    container_name: mongodb
    volumes:
      - /dev:/dev
      - ./data-node:/data/db
    command: mongod --noauth
